# Generated by Django 5.2.17 on 2026-09-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='credential_issuer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
