# Generated by Django 5.2.17 on 2026-09-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0005_projectt3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectT3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='credential_issuer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='repository_url',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
