# Generated by Django 5.2.17 on 2026-09-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0006_delete_projectt3_remove_project_credential_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
